//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazinoKlijent2.KazinoServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Karta", Namespace="http://schemas.datacontract.org/2004/07/KazinoServis")]
    [System.SerializableAttribute()]
    public partial class Karta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrojField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Broj {
            get {
                return this.BrojField;
            }
            set {
                if ((this.BrojField.Equals(value) != true)) {
                    this.BrojField = value;
                    this.RaisePropertyChanged("Broj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KazinoServis.IKazino")]
    public interface IKazino {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKazino/DijeliKartu", ReplyAction="http://tempuri.org/IKazino/DijeliKartuResponse")]
        KazinoKlijent2.KazinoServis.Karta DijeliKartu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKazino/DijeliKartu", ReplyAction="http://tempuri.org/IKazino/DijeliKartuResponse")]
        System.Threading.Tasks.Task<KazinoKlijent2.KazinoServis.Karta> DijeliKartuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKazino/BacamKartu", ReplyAction="http://tempuri.org/IKazino/BacamKartuResponse")]
        bool BacamKartu(KazinoKlijent2.KazinoServis.Karta karta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKazino/BacamKartu", ReplyAction="http://tempuri.org/IKazino/BacamKartuResponse")]
        System.Threading.Tasks.Task<bool> BacamKartuAsync(KazinoKlijent2.KazinoServis.Karta karta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKazino/SveBaceneKarte", ReplyAction="http://tempuri.org/IKazino/SveBaceneKarteResponse")]
        KazinoKlijent2.KazinoServis.Karta[] SveBaceneKarte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKazino/SveBaceneKarte", ReplyAction="http://tempuri.org/IKazino/SveBaceneKarteResponse")]
        System.Threading.Tasks.Task<KazinoKlijent2.KazinoServis.Karta[]> SveBaceneKarteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKazinoChannel : KazinoKlijent2.KazinoServis.IKazino, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KazinoClient : System.ServiceModel.ClientBase<KazinoKlijent2.KazinoServis.IKazino>, KazinoKlijent2.KazinoServis.IKazino {
        
        public KazinoClient() {
        }
        
        public KazinoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KazinoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KazinoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KazinoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KazinoKlijent2.KazinoServis.Karta DijeliKartu() {
            return base.Channel.DijeliKartu();
        }
        
        public System.Threading.Tasks.Task<KazinoKlijent2.KazinoServis.Karta> DijeliKartuAsync() {
            return base.Channel.DijeliKartuAsync();
        }
        
        public bool BacamKartu(KazinoKlijent2.KazinoServis.Karta karta) {
            return base.Channel.BacamKartu(karta);
        }
        
        public System.Threading.Tasks.Task<bool> BacamKartuAsync(KazinoKlijent2.KazinoServis.Karta karta) {
            return base.Channel.BacamKartuAsync(karta);
        }
        
        public KazinoKlijent2.KazinoServis.Karta[] SveBaceneKarte() {
            return base.Channel.SveBaceneKarte();
        }
        
        public System.Threading.Tasks.Task<KazinoKlijent2.KazinoServis.Karta[]> SveBaceneKarteAsync() {
            return base.Channel.SveBaceneKarteAsync();
        }
    }
}
