//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predavanje_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klub
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int Pozicija { get; set; }
        public int BrojBodova { get; set; }
        public Nullable<int> LigaId { get; set; }
    
        public virtual Liga Liga { get; set; }
    }
}
