//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.DijeliServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Karta", Namespace="http://schemas.datacontract.org/2004/07/WCFServis")]
    [System.SerializableAttribute()]
    public partial class Karta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Broj {
            get {
                return this.BrojField;
            }
            set {
                if ((this.BrojField.Equals(value) != true)) {
                    this.BrojField = value;
                    this.RaisePropertyChanged("Broj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip {
            get {
                return this.TipField;
            }
            set {
                if ((object.ReferenceEquals(this.TipField, value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DijeliServis.IDijeli")]
    public interface IDijeli {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDijeli/DajKartu", ReplyAction="http://tempuri.org/IDijeli/DajKartuResponse")]
        WCFClient.DijeliServis.Karta DajKartu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDijeli/DajKartu", ReplyAction="http://tempuri.org/IDijeli/DajKartuResponse")]
        System.Threading.Tasks.Task<WCFClient.DijeliServis.Karta> DajKartuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDijeli/PrimiKartu", ReplyAction="http://tempuri.org/IDijeli/PrimiKartuResponse")]
        bool PrimiKartu(WCFClient.DijeliServis.Karta k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDijeli/PrimiKartu", ReplyAction="http://tempuri.org/IDijeli/PrimiKartuResponse")]
        System.Threading.Tasks.Task<bool> PrimiKartuAsync(WCFClient.DijeliServis.Karta k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDijeliChannel : WCFClient.DijeliServis.IDijeli, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DijeliClient : System.ServiceModel.ClientBase<WCFClient.DijeliServis.IDijeli>, WCFClient.DijeliServis.IDijeli {
        
        public DijeliClient() {
        }
        
        public DijeliClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DijeliClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DijeliClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DijeliClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFClient.DijeliServis.Karta DajKartu() {
            return base.Channel.DajKartu();
        }
        
        public System.Threading.Tasks.Task<WCFClient.DijeliServis.Karta> DajKartuAsync() {
            return base.Channel.DajKartuAsync();
        }
        
        public bool PrimiKartu(WCFClient.DijeliServis.Karta k) {
            return base.Channel.PrimiKartu(k);
        }
        
        public System.Threading.Tasks.Task<bool> PrimiKartuAsync(WCFClient.DijeliServis.Karta k) {
            return base.Channel.PrimiKartuAsync(k);
        }
    }
}
