//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.WcfNasPrimjer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Riba", Namespace="http://schemas.datacontract.org/2004/07/WcfNasPrimjer")]
    [System.SerializableAttribute()]
    public partial class Riba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KolicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfNasPrimjer.IRibarnica")]
    public interface IRibarnica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRibarnica/DajSveRibe", ReplyAction="http://tempuri.org/IRibarnica/DajSveRibeResponse")]
        WCFClient.WcfNasPrimjer.Riba[] DajSveRibe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRibarnica/DajSveRibe", ReplyAction="http://tempuri.org/IRibarnica/DajSveRibeResponse")]
        System.Threading.Tasks.Task<WCFClient.WcfNasPrimjer.Riba[]> DajSveRibeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRibarnica/DodajRibu", ReplyAction="http://tempuri.org/IRibarnica/DodajRibuResponse")]
        bool DodajRibu(WCFClient.WcfNasPrimjer.Riba ribetina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRibarnica/DodajRibu", ReplyAction="http://tempuri.org/IRibarnica/DodajRibuResponse")]
        System.Threading.Tasks.Task<bool> DodajRibuAsync(WCFClient.WcfNasPrimjer.Riba ribetina);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRibarnicaChannel : WCFClient.WcfNasPrimjer.IRibarnica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RibarnicaClient : System.ServiceModel.ClientBase<WCFClient.WcfNasPrimjer.IRibarnica>, WCFClient.WcfNasPrimjer.IRibarnica {
        
        public RibarnicaClient() {
        }
        
        public RibarnicaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RibarnicaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RibarnicaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RibarnicaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFClient.WcfNasPrimjer.Riba[] DajSveRibe() {
            return base.Channel.DajSveRibe();
        }
        
        public System.Threading.Tasks.Task<WCFClient.WcfNasPrimjer.Riba[]> DajSveRibeAsync() {
            return base.Channel.DajSveRibeAsync();
        }
        
        public bool DodajRibu(WCFClient.WcfNasPrimjer.Riba ribetina) {
            return base.Channel.DodajRibu(ribetina);
        }
        
        public System.Threading.Tasks.Task<bool> DodajRibuAsync(WCFClient.WcfNasPrimjer.Riba ribetina) {
            return base.Channel.DodajRibuAsync(ribetina);
        }
    }
}
