//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predavanje_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igrac
    {
        public int id { get; set; }
        public string ime { get; set; }
        public int vrijednost { get; set; }
        public Nullable<int> klubId { get; set; }
    
        public virtual Klub Klub { get; set; }
    }
}
