//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pred8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kladionica
    {
        public Kladionica()
        {
            this.Par = new HashSet<Par>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<Par> Par { get; set; }
    }
}
