//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pred8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Par
    {
        public int parId { get; set; }
        public string naziv { get; set; }
        public double koeficijent { get; set; }
        public Nullable<int> kladId { get; set; }
    
        public virtual Kladionica Kladionica { get; set; }
    }
}
