//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.WcfPokerReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Karta", Namespace="http://schemas.datacontract.org/2004/07/WcfServis")]
    [System.SerializableAttribute()]
    public partial class Karta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrojField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Broj {
            get {
                return this.BrojField;
            }
            set {
                if ((this.BrojField.Equals(value) != true)) {
                    this.BrojField = value;
                    this.RaisePropertyChanged("Broj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfPokerReference.IPoker")]
    public interface IPoker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoker/Uzimamkartu", ReplyAction="http://tempuri.org/IPoker/UzimamkartuResponse")]
        WcfClient.WcfPokerReference.Karta Uzimamkartu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoker/Uzimamkartu", ReplyAction="http://tempuri.org/IPoker/UzimamkartuResponse")]
        System.Threading.Tasks.Task<WcfClient.WcfPokerReference.Karta> UzimamkartuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoker/BacamKartu", ReplyAction="http://tempuri.org/IPoker/BacamKartuResponse")]
        bool BacamKartu(WcfClient.WcfPokerReference.Karta karta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPoker/BacamKartu", ReplyAction="http://tempuri.org/IPoker/BacamKartuResponse")]
        System.Threading.Tasks.Task<bool> BacamKartuAsync(WcfClient.WcfPokerReference.Karta karta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPokerChannel : WcfClient.WcfPokerReference.IPoker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PokerClient : System.ServiceModel.ClientBase<WcfClient.WcfPokerReference.IPoker>, WcfClient.WcfPokerReference.IPoker {
        
        public PokerClient() {
        }
        
        public PokerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PokerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfClient.WcfPokerReference.Karta Uzimamkartu() {
            return base.Channel.Uzimamkartu();
        }
        
        public System.Threading.Tasks.Task<WcfClient.WcfPokerReference.Karta> UzimamkartuAsync() {
            return base.Channel.UzimamkartuAsync();
        }
        
        public bool BacamKartu(WcfClient.WcfPokerReference.Karta karta) {
            return base.Channel.BacamKartu(karta);
        }
        
        public System.Threading.Tasks.Task<bool> BacamKartuAsync(WcfClient.WcfPokerReference.Karta karta) {
            return base.Channel.BacamKartuAsync(karta);
        }
    }
}
