CREATE TABLE Parovi (
id INT IDENTITY PRIMARY KEY,
naziv NVARCHAR(40) NOT NULL,
koeficijent FLOAT NOT NULL,
klad_id INT FOREIGN KEY REFERENCES Kladionica(id)
)

CREATE TABLE Kladionica (
id INT IDENTITY,
naziv NVARCHAR(40) NOT NULL
)

ALTER TABLE Kladionica ADD CONSTRAINT pk_klad PRIMARY KEY(id)

