//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predavanje_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaraza
    {
        public int Id { get; set; }
        public int BrojZarezenih { get; set; }
        public int BrojIzlijecenih { get; set; }
        public int BrojUmrlih { get; set; }
        public int DrzavaId { get; set; }
    
        public virtual Drzave Drzave { get; set; }
    }
}
