//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predavanje8
{
    using System;
    using System.Collections.Generic;
    
    public partial class parovi
    {
        public int id { get; set; }
        public string naziv { get; set; }
        public double koef { get; set; }
        public Nullable<int> klad_id { get; set; }
    }
}
