//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.Diler {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Karta", Namespace="http://schemas.datacontract.org/2004/07/WCFServis")]
    [System.SerializableAttribute()]
    public partial class Karta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Broj {
            get {
                return this.BrojField;
            }
            set {
                if ((this.BrojField.Equals(value) != true)) {
                    this.BrojField = value;
                    this.RaisePropertyChanged("Broj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip {
            get {
                return this.TipField;
            }
            set {
                if ((object.ReferenceEquals(this.TipField, value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Diler.IDiler")]
    public interface IDiler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiler/DijeliKartu", ReplyAction="http://tempuri.org/IDiler/DijeliKartuResponse")]
        WCFClient.Diler.Karta DijeliKartu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiler/DijeliKartu", ReplyAction="http://tempuri.org/IDiler/DijeliKartuResponse")]
        System.Threading.Tasks.Task<WCFClient.Diler.Karta> DijeliKartuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiler/PrimiKartu", ReplyAction="http://tempuri.org/IDiler/PrimiKartuResponse")]
        bool PrimiKartu(WCFClient.Diler.Karta k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiler/PrimiKartu", ReplyAction="http://tempuri.org/IDiler/PrimiKartuResponse")]
        System.Threading.Tasks.Task<bool> PrimiKartuAsync(WCFClient.Diler.Karta k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDilerChannel : WCFClient.Diler.IDiler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DilerClient : System.ServiceModel.ClientBase<WCFClient.Diler.IDiler>, WCFClient.Diler.IDiler {
        
        public DilerClient() {
        }
        
        public DilerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DilerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DilerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DilerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFClient.Diler.Karta DijeliKartu() {
            return base.Channel.DijeliKartu();
        }
        
        public System.Threading.Tasks.Task<WCFClient.Diler.Karta> DijeliKartuAsync() {
            return base.Channel.DijeliKartuAsync();
        }
        
        public bool PrimiKartu(WCFClient.Diler.Karta k) {
            return base.Channel.PrimiKartu(k);
        }
        
        public System.Threading.Tasks.Task<bool> PrimiKartuAsync(WCFClient.Diler.Karta k) {
            return base.Channel.PrimiKartuAsync(k);
        }
    }
}
